"""Add Report model

Revision ID: 58d624fc362f
Revises: 6fa6c6685080
Create Date: 2025-06-29 13:14:26.948120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58d624fc362f'
down_revision: Union[str, None] = '6fa6c6685080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_advisor_id', 'reports', ['advisor_id'], unique=False)
    op.create_index('ix_reports_client_id', 'reports', ['client_id'], unique=False)
    op.create_index('ix_reports_generated_at', 'reports', ['generated_at'], unique=False)
    op.create_index('ix_reports_report_type', 'reports', ['report_type'], unique=False)
    op.drop_index('ix_assets_ticker_symbol', table_name='assets')
    op.create_index('ix_assets_ticker_symbol', 'assets', ['ticker_symbol'], unique=False)
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    op.drop_index('ix_assets_ticker_symbol', table_name='assets')
    op.create_index('ix_assets_ticker_symbol', 'assets', ['ticker_symbol'], unique=True)
    op.drop_index('ix_reports_report_type', table_name='reports')
    op.drop_index('ix_reports_generated_at', table_name='reports')
    op.drop_index('ix_reports_client_id', table_name='reports')
    op.drop_index('ix_reports_advisor_id', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
