"""add_portfolio_name_to_clients

Revision ID: 5be037e90934
Revises: 65819414d634
Create Date: 2025-06-29 23:58:22.405683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5be037e90934'
down_revision: Union[str, None] = '65819414d634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('portfolio_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    op.drop_column('clients', 'portfolio_name')
    # ### end Alembic commands ###
