"""add_username_to_users

Revision ID: 6fa6c6685080
Revises: ed1b32c54319
Create Date: 2025-06-29 12:59:56.353565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fa6c6685080'
down_revision: Union[str, None] = 'ed1b32c54319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('users', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    
    # Update existing users with default usernames based on email
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE users SET username = SPLIT_PART(email, '@', 1) WHERE username IS NULL"))
    
    # Now make the column NOT NULL and unique
    op.alter_column('users', 'username', nullable=False)
    
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
