"""Add PortfolioSnapshot table

Revision ID: 8fed73f9da88
Revises: 58d624fc362f
Create Date: 2025-06-29 14:04:36.776600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fed73f9da88'
down_revision: Union[str, None] = '58d624fc362f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_snapshots_portfolio_id', 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_snapshots_portfolio_timestamp', 'portfolio_snapshots', ['portfolio_id', 'timestamp'], unique=False)
    op.create_index('ix_portfolio_snapshots_timestamp', 'portfolio_snapshots', ['timestamp'], unique=False)
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    op.drop_index('ix_portfolio_snapshots_timestamp', table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_portfolio_timestamp', table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_portfolio_id', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
