"""add_sector_field_to_asset_model

Revision ID: d563441ca0de
Revises: abc123def456
Create Date: 2025-06-30 01:22:58.991108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd563441ca0de'
down_revision: Union[str, None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('sector', sa.String(length=100), nullable=True))
    op.drop_constraint('model_portfolio_positions_model_portfolio_id_asset_id_key', 'model_portfolio_positions', type_='unique')
    op.create_index('uq_model_portfolio_asset', 'model_portfolio_positions', ['model_portfolio_id', 'asset_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_model_portfolio_asset', table_name='model_portfolio_positions')
    op.create_unique_constraint('model_portfolio_positions_model_portfolio_id_asset_id_key', 'model_portfolio_positions', ['model_portfolio_id', 'asset_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'sector')
    # ### end Alembic commands ###
