"""initial schema (all models explicit import)

Revision ID: e0b602d1ae2f
Revises: 
Create Date: 2025-07-21 20:37:27.657116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0b602d1ae2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'ETF', 'BOND', name='assettype'), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_symbol')
    )
    op.create_index('ix_assets_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_index('ix_assets_name', 'assets', ['name'], unique=False)
    op.create_index('ix_assets_sector', 'assets', ['sector'], unique=False)
    op.create_index('ix_assets_ticker_name', 'assets', ['ticker_symbol', 'name'], unique=False)
    op.create_index('ix_assets_ticker_symbol', 'assets', ['ticker_symbol'], unique=False)
    op.create_table('model_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_profile', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskprofile'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_portfolios_created_at', 'model_portfolios', ['created_at'], unique=False)
    op.create_index('ix_model_portfolios_name', 'model_portfolios', ['name'], unique=False)
    op.create_index('ix_model_portfolios_risk_name', 'model_portfolios', ['risk_profile', 'name'], unique=False)
    op.create_index('ix_model_portfolios_risk_profile', 'model_portfolios', ['risk_profile'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SENIOR_ADVISOR', 'JUNIOR_ADVISOR', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_email_role', 'users', ['email', 'role'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_profile', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskprofile'), nullable=False),
    sa.Column('status', sa.Enum('prospect', 'contacted', 'first_meeting', 'second_meeting', 'opening', 'onboarding', 'reschedule', 'active_investor', 'active_insured', 'dormant', name='clientstatus'), nullable=False),
    sa.Column('lead_source', sa.Enum('referral', 'social_media', 'event', 'organic', 'other', name='leadsource'), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('live_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portfolio_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referred_by_client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referred_by_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_clients_created_at', 'clients', ['created_at'], unique=False)
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    op.create_index('ix_clients_email_owner', 'clients', ['email', 'owner_id'], unique=False)
    op.create_index('ix_clients_owner_id', 'clients', ['owner_id'], unique=False)
    op.create_index('ix_clients_owner_status', 'clients', ['owner_id', 'status'], unique=False)
    op.create_index('ix_clients_risk_profile', 'clients', ['risk_profile'], unique=False)
    op.create_index('ix_clients_status', 'clients', ['status'], unique=False)
    op.create_index('ix_clients_updated_at', 'clients', ['updated_at'], unique=False)
    op.create_table('model_portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model_portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['model_portfolio_id'], ['model_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_portfolio_positions_asset_id', 'model_portfolio_positions', ['asset_id'], unique=False)
    op.create_index('ix_model_portfolio_positions_model_portfolio_id', 'model_portfolio_positions', ['model_portfolio_id'], unique=False)
    op.create_index('ix_model_portfolio_positions_portfolio_asset', 'model_portfolio_positions', ['model_portfolio_id', 'asset_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('client_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_activities_client_created', 'client_activities', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_client_activities_client_id', 'client_activities', ['client_id'], unique=False)
    op.create_index('ix_client_activities_created_at', 'client_activities', ['created_at'], unique=False)
    op.create_index('ix_client_activities_created_by', 'client_activities', ['created_by'], unique=False)
    op.create_index('ix_client_activities_type', 'client_activities', ['activity_type'], unique=False)
    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_notes_client_created', 'client_notes', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_client_notes_client_id', 'client_notes', ['client_id'], unique=False)
    op.create_index('ix_client_notes_created_at', 'client_notes', ['created_at'], unique=False)
    op.create_index('ix_client_notes_created_by', 'client_notes', ['created_by'], unique=False)
    op.create_index('ix_client_notes_updated_at', 'client_notes', ['updated_at'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insurance_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_index('ix_insurance_policies_client_id', 'insurance_policies', ['client_id'], unique=False)
    op.create_index('ix_insurance_policies_client_type', 'insurance_policies', ['client_id', 'insurance_type'], unique=False)
    op.create_index('ix_insurance_policies_coverage_amount', 'insurance_policies', ['coverage_amount'], unique=False)
    op.create_index('ix_insurance_policies_insurance_type', 'insurance_policies', ['insurance_type'], unique=False)
    op.create_index('ix_insurance_policies_policy_number', 'insurance_policies', ['policy_number'], unique=False)
    op.create_table('investment_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aum', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investment_accounts_aum', 'investment_accounts', ['aum'], unique=False)
    op.create_index('ix_investment_accounts_client_id', 'investment_accounts', ['client_id'], unique=False)
    op.create_index('ix_investment_accounts_client_platform', 'investment_accounts', ['client_id', 'platform'], unique=False)
    op.create_index('ix_investment_accounts_platform', 'investment_accounts', ['platform'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_client_id', 'portfolios', ['client_id'], unique=False)
    op.create_index('ix_portfolios_client_value', 'portfolios', ['client_id', 'current_value'], unique=False)
    op.create_index('ix_portfolios_created_at', 'portfolios', ['created_at'], unique=False)
    op.create_index('ix_portfolios_current_value', 'portfolios', ['current_value'], unique=False)
    op.create_index('ix_portfolios_updated_at', 'portfolios', ['updated_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_advisor_id', 'reports', ['advisor_id'], unique=False)
    op.create_index('ix_reports_client_advisor', 'reports', ['client_id', 'advisor_id'], unique=False)
    op.create_index('ix_reports_client_id', 'reports', ['client_id'], unique=False)
    op.create_index('ix_reports_generated_at', 'reports', ['generated_at'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_snapshots_portfolio_id', 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_snapshots_portfolio_timestamp', 'portfolio_snapshots', ['portfolio_id', 'timestamp'], unique=False)
    op.create_index('ix_portfolio_snapshots_timestamp', 'portfolio_snapshots', ['timestamp'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_asset_id', 'positions', ['asset_id'], unique=False)
    op.create_index('ix_positions_current_price', 'positions', ['current_price'], unique=False)
    op.create_index('ix_positions_portfolio_asset', 'positions', ['portfolio_id', 'asset_id'], unique=False)
    op.create_index('ix_positions_portfolio_id', 'positions', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_portfolio_id', table_name='positions')
    op.drop_index('ix_positions_portfolio_asset', table_name='positions')
    op.drop_index('ix_positions_current_price', table_name='positions')
    op.drop_index('ix_positions_asset_id', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_portfolio_snapshots_timestamp', table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_portfolio_timestamp', table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_portfolio_id', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_reports_generated_at', table_name='reports')
    op.drop_index('ix_reports_client_id', table_name='reports')
    op.drop_index('ix_reports_client_advisor', table_name='reports')
    op.drop_index('ix_reports_advisor_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_portfolios_updated_at', table_name='portfolios')
    op.drop_index('ix_portfolios_current_value', table_name='portfolios')
    op.drop_index('ix_portfolios_created_at', table_name='portfolios')
    op.drop_index('ix_portfolios_client_value', table_name='portfolios')
    op.drop_index('ix_portfolios_client_id', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_investment_accounts_platform', table_name='investment_accounts')
    op.drop_index('ix_investment_accounts_client_platform', table_name='investment_accounts')
    op.drop_index('ix_investment_accounts_client_id', table_name='investment_accounts')
    op.drop_index('ix_investment_accounts_aum', table_name='investment_accounts')
    op.drop_table('investment_accounts')
    op.drop_index('ix_insurance_policies_policy_number', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_insurance_type', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_coverage_amount', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_client_type', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_client_id', table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index('ix_client_notes_updated_at', table_name='client_notes')
    op.drop_index('ix_client_notes_created_by', table_name='client_notes')
    op.drop_index('ix_client_notes_created_at', table_name='client_notes')
    op.drop_index('ix_client_notes_client_id', table_name='client_notes')
    op.drop_index('ix_client_notes_client_created', table_name='client_notes')
    op.drop_table('client_notes')
    op.drop_index('ix_client_activities_type', table_name='client_activities')
    op.drop_index('ix_client_activities_created_by', table_name='client_activities')
    op.drop_index('ix_client_activities_created_at', table_name='client_activities')
    op.drop_index('ix_client_activities_client_id', table_name='client_activities')
    op.drop_index('ix_client_activities_client_created', table_name='client_activities')
    op.drop_table('client_activities')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_model_portfolio_positions_portfolio_asset', table_name='model_portfolio_positions')
    op.drop_index('ix_model_portfolio_positions_model_portfolio_id', table_name='model_portfolio_positions')
    op.drop_index('ix_model_portfolio_positions_asset_id', table_name='model_portfolio_positions')
    op.drop_table('model_portfolio_positions')
    op.drop_index('ix_clients_updated_at', table_name='clients')
    op.drop_index('ix_clients_status', table_name='clients')
    op.drop_index('ix_clients_risk_profile', table_name='clients')
    op.drop_index('ix_clients_owner_status', table_name='clients')
    op.drop_index('ix_clients_owner_id', table_name='clients')
    op.drop_index('ix_clients_email_owner', table_name='clients')
    op.drop_index('ix_clients_email', table_name='clients')
    op.drop_index('ix_clients_created_at', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_model_portfolios_risk_profile', table_name='model_portfolios')
    op.drop_index('ix_model_portfolios_risk_name', table_name='model_portfolios')
    op.drop_index('ix_model_portfolios_name', table_name='model_portfolios')
    op.drop_index('ix_model_portfolios_created_at', table_name='model_portfolios')
    op.drop_table('model_portfolios')
    op.drop_index('ix_assets_ticker_symbol', table_name='assets')
    op.drop_index('ix_assets_ticker_name', table_name='assets')
    op.drop_index('ix_assets_sector', table_name='assets')
    op.drop_index('ix_assets_name', table_name='assets')
    op.drop_index('ix_assets_asset_type', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
