"""Create advanced CRM models with investment accounts and insurance policies

Revision ID: e84388e79158
Revises: 8fed73f9da88
Create Date: 2025-06-29 14:53:27.854583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e84388e79158'
down_revision: Union[str, None] = '8fed73f9da88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enum types first
    clientstatus = sa.Enum('prospect', 'contacted', 'onboarding', 'active_investor', 'active_insured', 'dormant', name='clientstatus')
    clientstatus.create(op.get_bind())
    
    leadsource = sa.Enum('referral', 'social_media', 'event', 'organic', 'other', name='leadsource')
    leadsource.create(op.get_bind())
    
    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('insurance_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insurance_policies_client_id', 'insurance_policies', ['client_id'], unique=False)
    op.create_index('ix_insurance_policies_insurance_type', 'insurance_policies', ['insurance_type'], unique=False)
    op.create_index('ix_insurance_policies_policy_number', 'insurance_policies', ['policy_number'], unique=False)
    op.create_table('investment_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('aum', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investment_accounts_account_number', 'investment_accounts', ['account_number'], unique=False)
    op.create_index('ix_investment_accounts_client_id', 'investment_accounts', ['client_id'], unique=False)
    op.create_index('ix_investment_accounts_platform', 'investment_accounts', ['platform'], unique=False)
    op.drop_index('ix_assets_ticker_symbol', table_name='assets')
    op.create_index(op.f('ix_assets_ticker_symbol'), 'assets', ['ticker_symbol'], unique=True)
    op.add_column('clients', sa.Column('status', sa.Enum('prospect', 'contacted', 'onboarding', 'active_investor', 'active_insured', 'dormant', name='clientstatus'), nullable=False))
    op.add_column('clients', sa.Column('lead_source', sa.Enum('referral', 'social_media', 'event', 'organic', 'other', name='leadsource'), nullable=True))
    op.add_column('clients', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('clients', sa.Column('referred_by_client_id', sa.Integer(), nullable=True))
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index('ix_clients_lead_source', 'clients', ['lead_source'], unique=False)
    op.create_index('ix_clients_referred_by_client_id', 'clients', ['referred_by_client_id'], unique=False)
    op.create_index('ix_clients_status', 'clients', ['status'], unique=False)
    op.create_foreign_key(None, 'clients', 'clients', ['referred_by_client_id'], ['id'])
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index('ix_clients_status', table_name='clients')
    op.drop_index('ix_clients_referred_by_client_id', table_name='clients')
    op.drop_index('ix_clients_lead_source', table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    op.drop_column('clients', 'referred_by_client_id')
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'lead_source')
    op.drop_column('clients', 'status')
    op.drop_index(op.f('ix_assets_ticker_symbol'), table_name='assets')
    op.create_index('ix_assets_ticker_symbol', 'assets', ['ticker_symbol'], unique=False)
    op.drop_index('ix_investment_accounts_platform', table_name='investment_accounts')
    op.drop_index('ix_investment_accounts_client_id', table_name='investment_accounts')
    op.drop_index('ix_investment_accounts_account_number', table_name='investment_accounts')
    op.drop_table('investment_accounts')
    op.drop_index('ix_insurance_policies_policy_number', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_insurance_type', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_client_id', table_name='insurance_policies')
    op.drop_table('insurance_policies')
    
    # Drop Enum types
    sa.Enum(name='clientstatus').drop(op.get_bind())
    sa.Enum(name='leadsource').drop(op.get_bind())
    # ### end Alembic commands ###
