"""Create all tables

Revision ID: ed1b32c54319
Revises: db8ea4bed50c
Create Date: 2025-06-28 13:31:54.963882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed1b32c54319'
down_revision: Union[str, None] = 'db8ea4bed50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'ETF', 'BOND', name='assettype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_ticker_symbol'), 'assets', ['ticker_symbol'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('risk_profile', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskprofile'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    op.create_index('ix_clients_owner_id', 'clients', ['owner_id'], unique=False)
    op.create_index('ix_clients_risk_profile', 'clients', ['risk_profile'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_client_id', 'portfolios', ['client_id'], unique=False)
    op.create_index('ix_portfolios_name', 'portfolios', ['name'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_asset_id', 'positions', ['asset_id'], unique=False)
    op.create_index('ix_positions_portfolio_asset', 'positions', ['portfolio_id', 'asset_id'], unique=True)
    op.create_index('ix_positions_portfolio_id', 'positions', ['portfolio_id'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index('ix_positions_portfolio_id', table_name='positions')
    op.drop_index('ix_positions_portfolio_asset', table_name='positions')
    op.drop_index('ix_positions_asset_id', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_portfolios_name', table_name='portfolios')
    op.drop_index('ix_portfolios_client_id', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_clients_risk_profile', table_name='clients')
    op.drop_index('ix_clients_owner_id', table_name='clients')
    op.drop_index('ix_clients_email', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_assets_ticker_symbol'), table_name='assets')
    op.drop_index('ix_assets_asset_type', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
